#!/opt/Anaconda3/2022.05/bin_nompi/python
import sys
import os
import time
from tool import time_stamp, find_file_path


history_task_path = find_file_path('history_task.dat')
queue_info_path = find_file_path('queue_info.dat')

#读取history_task.json文件，查看已经提交的任务的task_id,接下来提交的这个任务的task_id就是已经提交的任务的task_id+1
with open(history_task_path, 'r') as f:
    lines = f.readlines()
    if len(lines) == 0:
        task_id = 1
    else:
        task_id = int(lines[-1].split(',')[0]) + 1

job_name = sys.argv[1]
workdir = os.getcwd()
run_time = time_stamp(0)
state = 'PD'
date = int(time.time())
nodelist = '(Priority)'
task_info = [task_id, job_name, state,  run_time, workdir, date, nodelist]


#将task_info写入queue_info.dat文件
with open(queue_info_path, 'a') as f:
    #去掉[]和''，并且用,分隔
    f.write(str(task_info).strip('[]').replace("'", "") + '\n')

with open(history_task_path, 'a') as f:
    #去掉[]和''，并且用,分隔
    f.write(str(task_info).strip('[]').replace("'", "") + '\n')